const productList = [
  {
    id: 1,
    name: "Perde e vetme e panelit",
    category: "Tepiha",
    price: 828,
    stock: 25,
  },
  {
    id: 2,
    name: "Cifti i perdeve të panelit",
    category: "Tepiha",
    price: 144,
    stock: 43,
  },
  {
    id: 3,
    name: "Perde me krahët e ngushtë",
    category: "Tepiha",
    price: 28,
    stock: 123,
  },
  {
    id: 4,
    name: "Perde me kuti të ngushtë",
    category: "Tepiha",
    price: 85,
    stock: 33,
  },
  {
    id: 5,
    name: "Perde me kuti të goblet",
    category: "Tepiha",
    price: 113,
    stock: 11,
  },
  {
    id: 6,
    name: "Perde me laps të lapsit",
    category: "Tepiha",
    price: 28,
    stock: 123,
  },
  {
    id: 7,
    name: "Perde me vrimë",
    category: "Tepiha",
    price: 25,
    stock: 10,
  },
  {
    id: 8,
    name: "Perde me varg të kryqëzuar",
    category: "Tepiha",
    price: 92,
    stock: 323,
  },
  {
    id: 9,
    name: "Perde me vathë",
    category: "Tepiha",
    price: 35,
    stock: 52,
  },
  {
    id: 10,
    name: "Perde me fije",
    category: "Tepiha",
    price: 13,
    stock: 25,
  },
  {
    id: 11,
    name: "Perde driteheqëse",
    category: "Tepiha",
    price: 828,
    stock: 30,
  },
  {
    id: 12,
    name: "Perde të energjisë së efektshme",
    category: "Tepiha",
    price: 144,
    stock: 20,
  },
  {
    id: 13,
    name: "Perde për dritaren e dritës",
    category: "Tepiha",
    price: 28,
    stock: 19,
  },
  {
    id: 14,
    name: "Perde për dritaren",
    category: "Tepiha",
    price: 85,
    stock: 30,
  },
  {
    id: 15,
    name: "Perde për dritaren e femrave",
    category: "Tepiha",
    price: 113,
    stock: 75,
  },
  {
    id: 17,
    name: "Perde të kafenes",
    category: "Tepiha",
    price: 25,
    stock: 13,
  },
  {
    id: 18,
    name: "Perde të pastra",
    category: "Tepiha",
    price: 92,
    stock: 18,
  },
  {
    id: 19,
    name: "Perde për dritare",
    category: "Tepiha",
    price: 35,
    stock: 27,
  },
  {
    id: 20,
    name: "Perde të hapura",
    category: "Tepiha",
    price: 13,
    stock: 43,
  },
];

export default productList;
